# Everytime a change is pushed to github, travis opens a python server
# Makes the docker service available, use pip to install docker-compose
# then it will run our script
# if this fails, it will fail the build and send a notification
language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
